name: Build, Version, and Publish

on:
  push:
    branches:
      - master

jobs:
  build-version-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build TypeScript
        run: yarn build

      - name: Install jq
        run: sudo apt-get install jq

      - name: Bump version and create a tag
        id: create_new_tag
        run: |
          git config --local user.email "joelngozo@gmail.com"
          git config --local user.name "@JoelFickson"
          npm version minor -m "Bump version to %s"
          echo "NEW_VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV
          git push origin HEAD:master --follow-tags

      - name: Set up Node.js for publish
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
